name = "la-nevera-borrado"
main = "src/index.js"
compatibility_date = "2024-11-01"

[vars]
ORIGENES_PERMITIDOS = "https://nctrl12.github.io"
AIRTABLE_BASE_ID = "appOANzgalvLugPP1"
AIRTABLE_TABLE_ID = "tblj3eagIgj8WOc5d"
